// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcufl71esXvr5cY6PCf5vmgl9XcDWQ5eM',
    appId: '1:956403804800:web:34e85dcd59137ca58e9465',
    messagingSenderId: '956403804800',
    projectId: 'lamzudb-78198',
    authDomain: 'lamzudb-78198.firebaseapp.com',
    storageBucket: 'lamzudb-78198.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO1eYiPnQZVr9rxesnfFWt07wwe1_E1Rc',
    appId: '1:956403804800:android:34bd02cf2a86a06b8e9465',
    messagingSenderId: '956403804800',
    projectId: 'lamzudb-78198',
    storageBucket: 'lamzudb-78198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9qk1dNHEoPpBzgpaFHUueMFVqS3bUbk',
    appId: '1:956403804800:ios:62e0f34b89c08a3f8e9465',
    messagingSenderId: '956403804800',
    projectId: 'lamzudb-78198',
    storageBucket: 'lamzudb-78198.appspot.com',
    iosBundleId: 'com.example.flutterFlowTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9qk1dNHEoPpBzgpaFHUueMFVqS3bUbk',
    appId: '1:956403804800:ios:3924df7f31f3d4d68e9465',
    messagingSenderId: '956403804800',
    projectId: 'lamzudb-78198',
    storageBucket: 'lamzudb-78198.appspot.com',
    iosBundleId: 'com.example.flutterFlowTest.RunnerTests',
  );
}
