// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhWY1HGosTfnUOfRRGE42Yra9P8-wnxkk',
    appId: '1:716812125304:web:b4c8ad73b2733fafa5198d',
    messagingSenderId: '716812125304',
    projectId: 'adminpage-fd5c4',
    authDomain: 'adminpage-fd5c4.firebaseapp.com',
    storageBucket: 'adminpage-fd5c4.appspot.com',
    measurementId: 'G-SPWTFPERGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCffWUky7eHqquAJ8e0jsq-OU7SaHlyY2k',
    appId: '1:716812125304:android:3d71b4a3a10ac981a5198d',
    messagingSenderId: '716812125304',
    projectId: 'adminpage-fd5c4',
    storageBucket: 'adminpage-fd5c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcePN43vxXIs6bXt_Muk3jEA0uQKG6khM',
    appId: '1:716812125304:ios:b3204a1a8428e4d5a5198d',
    messagingSenderId: '716812125304',
    projectId: 'adminpage-fd5c4',
    storageBucket: 'adminpage-fd5c4.appspot.com',
    iosBundleId: 'com.example.adminPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcePN43vxXIs6bXt_Muk3jEA0uQKG6khM',
    appId: '1:716812125304:ios:f96febee2e9627d8a5198d',
    messagingSenderId: '716812125304',
    projectId: 'adminpage-fd5c4',
    storageBucket: 'adminpage-fd5c4.appspot.com',
    iosBundleId: 'com.example.adminPage.RunnerTests',
  );
}
